name: 'fprime-setup-rpi-build'
description: 'Setup RPI build for use with F´'
author: 'F´'
inputs:
  toolchain:
    description: "Toolchain to download and unpack to RPI_TOOLCHAIN_DIR"
    required: true
    # Linaro 7.5 is Reliable for RPI as of Late 2022 Releases
    default: "https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz"
  sysrootImage:
    description: "SYSROOT XY compressed .img with Second Partition Being Linux Filesystem"
    required: false
    default: ""
  sysrootLocation:
    description: "Directory to place sysroot within"
    required: false
    default: /tmp/rpi-sysroot
runs:
  using: "composite"
  steps:
  - name: "Download and Extract to RPI_TOOLCHAIN_DIR"
    run: |
      mkdir -p ${RPI_TOOLCHAIN_DIR} 
      wget -q ${{ inputs.toolchain }}
      tar -xf $(basename ${{ inputs.toolchain}}) -C ${RPI_TOOLCHAIN_DIR} --strip-components 1
    shell: bash
  - name: "Download and Extract SYSROOT Image as XZ"
    if: ${{ inputs.sysrootImage != '' }}
    run: |
      wget -qO- ${{ inputs.sysrootImage }}
      unxz "$(basename ${{ inputs.sysrootImage }})"
    shell: bash
  - name: "Mount Second Partition Image as Loopback"
    if: ${{ inputs.sysrootImage != '' }}
    run: |
      mkdir ${{ inputs.sysrootLocation }}
      LOOP_BACK_DEVICE="$(sudo losetup -Pr --show -f $(basename ${{ inputs.sysrootImage }} .xz))"
      sudo mount "${LOOP_BACK_DEVICE}p2" "${{ inputs.sysrootLocation }}"
    shell: bash
