name: 'fprime-setup-rpi-sysroot'
description: 'Setup RPI sysroot for use with F´'
author: 'F´'
inputs:
  location:
    description: "Directory to place sysroot within"
    required: true
    default: $GITHUB_WORKSPACE/rpi-sysroot
  image:
    description: "Image to download"
    required: true
    default: "https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-09-26/2022-09-22-raspios-bullseye-armhf-lite.img.xz"
runs:
  using: "composite"
  steps:
  - name: "Download and Extract RPI Image"
    run: |
      wget -q ${{ inputs.image }}
      unxz "$(basename ${{ inputs.image }})"
    shell: bash
  - name: "Mount Second Partition Image as Loopback"
    run: |
      mkdir ${{ inputs.location }}
      LOOP_BACK_DEVICE="$(sudo losetup -Pr --show -f $(basename ${{ inputs.image }} .xz))"
      sudo mount "${LOOP_BACK_DEVICE}p2" "${{ inputs.location }}"
    shell: bash
  - name: "List SYSROOT Contents"
    run: |
      ls "${{ inputs.location }}"
    shell: bash
